### ISSUE TITLE
SSL issues

### ISSUE THREAD

**Issue by puppycodes** [datproject/datBase#634]
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
on Chrome Version 66.0.3359.139 (Official Build) (64-bit)
and Firefox Version 59.02

is this just me or a server issue?

**Comment by joehand** [comment]
Thanks for checking! This is us. I will switch back to the old nameservers while the SSL stuff gets resolved. Once the old nameservers propagate again, it should be fixed.
